/**
 * Copy de marca Atelier.
 * Nunca: pedido, producto, proveedor (en UI de usuario).
 * Sí: obra, encargo, artista, cliente. Ej.: Encargar una obra / Encargo #184 / Private commission.
 */
export const ATELIER_COPY = {
  brand: "Horytek",
  wordmark: "Atelier",
  brandLockup: "Horytek Atelier",
  tagline: "Tu idea. Su trazo.",
  taglineFull: "Tu idea. Su trazo. Una obra.",
  ideaExists: "Tu idea ahora existe",
  seeIdeaBecome: "Mira cómo la idea se vuelve real",
  conceptLead: "No pides un producto. Encargas un trazo.",
  conceptBody:
    "El artista responde con una propuesta. Tú confirmas el encargo. La obra llega con su nombre, no como un archivo suelto.",
  ctaCommission: "Encargar una obra",
  ctaDiscover: "Descubrir artistas",
  composerSoon: "El brief se escribe aquí",
  composerSoonBody:
    "Pronto: la idea, el estilo, las referencias y el presupuesto en un solo gesto. La ruta del encargo ya existe.",
  artworkDone: "Obra terminada",
  privateCommission: "Private commission",
  login: "Ingresar",
  discover: "Descubrir",
  artists: "Artistas",
  commission: "Encargar",
  yourAtelier: "Tu Atelier",
  yourStudio: "Tu estudio",
  emptyAtelier: "Todavía no hay ideas en tu Atelier",
  emptyAtelierBody: "Cuando encargues una obra, el proceso vive aquí: brief, propuesta y entrega.",
  emptyBoard: "Nadie ha publicado un brief todavía",
  emptyBoardBody: "Cuando un cliente abra un encargo al tablero, aparecerá aquí para cotizar.",
  emptyGallery: "Aún no hay obras en esta galería",
  emptyGalleryBody: "Vuelve más tarde o encarga una obra a este artista.",
  processInterrupted: "Algo interrumpió el proceso creativo",
  processInterruptedBody: "Inténtalo de nuevo en un momento. Tu encargo no se perdió.",
  fileUnavailable: "Esta obra ya no está disponible",
  dropReferences: "Suelta referencias aquí",
  dropDelivery: "Suelta la obra aquí",
  acceptProposal: (amount: string) => `Aceptar propuesta de ${amount}`,
  approveComplete: "Aprobar y completar encargo",
  payMercadoPago: "Pagar con Mercado Pago",
  registerClient: "Solicitar un dibujo",
  registerCreator: "Dibujar y aceptar encargos",
  openBoard: "Abierto al tablero",
  directedBrief: "Dirigido a este artista",
  rejectProposal: "Rechazar propuesta",
  startArtwork: "Empezar la obra",
  sendSketch: "Enviar boceto a revisión",
  presentArtwork: "Presentar la obra",
  requestRevision: "Pedir una revisión",
  noRevisionsLeft: "No quedan revisiones incluidas",
  previewArtwork: "Vista previa",
  downloadOriginal: "Descargar original",
  myStudio: "Mi estudio",
  explore: "Explorar",
  home: "Inicio",
  jobs: "Trabajos",
  briefs: "Solicitudes",
  orders: "Encargos",
  profile: "Perfil",
  myProfile: "Mi perfil",
  editFicha: "Editar",
  help: "Ayuda",
  logout: "Cerrar sesión",
  logoutConfirm: "¿Cerrar sesión?",
  logoutConfirmBody: "Saldrás de Atelier en este aparato. Tus encargos siguen en tu ficha.",
  logoutStay: "Quedarme",
  logoutGo: "Cerrar sesión",
  mesa: "Mesa",
  summary: "Resumen",
  users: "Usuarios",
  commissionRule: "Comisión",
  collapseMenu: "Colapsar menú",
  expandMenu: "Expandir menú",
  openMenu: "Abrir menú",
  filterFree: "Libres",
  filterDirected: "Para ti",
  filterQuoted: "Ya cotizadas",
  filterAll: "Todas",
  boardFree: "Solicitudes libres",
  boardDirected: "Te las pidieron a ti",
  boardQuoted: "Ya cotizadas",
  boardAll: "Todas las solicitudes",
  boardFreeBody: "Briefs abiertos al tablero. Una propuesta por brief.",
  boardDirectedBody: "Clientes que encargaron directo a tu estudio.",
  boardQuotedBody: "Propuestas enviadas. Esperando respuesta del cliente.",
  boardAllBody: "Libres, dirigidas y las que ya cotizaste.",
  emptyFree: "No hay solicitudes libres ahora",
  emptyFreeBody: "Cuando un cliente publique al tablero, aparece aquí para cotizar.",
  emptyDirected: "Nadie te pidió un brief todavía",
  emptyDirectedBody: "Los encargos dirigidos a tu estudio viven aquí.",
  emptyQuoted: "Todavía no enviaste una propuesta",
  emptyQuotedBody: "Cotiza un brief libre o uno que te pidieron a ti.",
  pickBrief: "Elige un brief de la lista para leerlo y cotizar.",
} as const;

export function formatCommissionId(id: number | string) {
  return `Encargo #${id}`;
}
