# Generated by Django 5.0.3 on 2024-07-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('iddetalle_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'db_table': 'detalle_ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('iddetalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idingreso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=20)),
                ('serie_comprobante', models.CharField(blank=True, max_length=7, null=True)),
                ('num_comprobante', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=11)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=20)),
                ('serie_comprobante', models.CharField(blank=True, max_length=7, null=True)),
                ('num_comprobante', models.CharField(max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
