// Constantes de acciones para logs del sistema (solo frontend)
export const LOG_ACTIONS = {
  LOGIN_OK: 'LOGIN_OK',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  USUARIO_BLOQUEAR: 'USUARIO_BLOQUEAR',
  USUARIO_DESBLOQUEAR: 'USUARIO_DESBLOQUEAR',
  USUARIO_CAMBIAR_CONTRASENA: 'USUARIO_CAMBIAR_CONTRASENA',
  VENTA_CREAR: 'VENTA_CREAR',
  VENTA_ANULAR: 'VENTA_ANULAR',
  COMPROBANTE_EMITIR: 'COMPROBANTE_EMITIR',
  SUNAT_ENVIAR: 'SUNAT_ENVIAR',
  SUNAT_ACEPTADA: 'SUNAT_ACEPTADA',
  SUNAT_RECHAZADA: 'SUNAT_RECHAZADA',
  NOTA_INGRESO_CREAR: 'NOTA_INGRESO_CREAR',
  NOTA_SALIDA_CREAR: 'NOTA_SALIDA_CREAR',
  NOTA_ANULAR: 'NOTA_ANULAR',
  GUIA_CREAR: 'GUIA_CREAR',
  GUIA_ANULAR: 'GUIA_ANULAR',
  CLIENTE_CREAR: 'CLIENTE_CREAR',
  CLIENTE_EDITAR: 'CLIENTE_EDITAR',
  PRODUCTO_CAMBIO_PRECIO: 'PRODUCTO_CAMBIO_PRECIO'
};
