import type {
  DemoTheme,
  ExperienceId,
  LandingAccent,
  LandingCopy,
  LandingPricingModule,
  LandingProductModule,
  LandingSectionId,
} from "./landingModule.types";
import { HORYTEK_PRODUCTS } from "@/features/platform/catalog/horytekProducts";
import { SALES_WHATSAPP_URL } from "../data/landing.data";
import { getNarrative } from "./content/productNarratives";

type CopyInput = Omit<LandingCopy, "story" | "scenario" | "antiConfusion"> &
  Partial<Pick<LandingCopy, "story" | "scenario" | "antiConfusion">>;

function tone(
  accent: string,
  surface: string,
  ctaBand: string,
  demoTheme: DemoTheme,
): LandingAccent {
  return {
    accent,
    surface,
    ink: "#1c1917",
    headerBorder: `${accent}33`,
    headerBg: `${accent}14`,
    ctaClass: "text-white",
    sectionTint: `${accent}0d`,
    labelClass: "",
    ctaBand,
    demoTheme,
  };
}

function plans(
  eyebrow: string,
  title: string,
  body: string,
  layout: LandingPricingModule["layout"],
  items: LandingPricingModule["plans"],
  footnote?: string,
): LandingPricingModule {
  return { eyebrow, title, body, billingToggle: "none", layout, plans: items, footnote };
}

function mod(
  productId: string,
  experienceId: ExperienceId,
  accentVal: LandingAccent,
  sectionOrder: LandingSectionId[],
  copy: CopyInput,
  pricing: LandingPricingModule,
  loginHref: string,
  motions: LandingProductModule["interaction"]["motions"],
  typography?: LandingProductModule["typography"],
): LandingProductModule {
  const catalog = HORYTEK_PRODUCTS.find((p) => p.id === productId);
  const narrative = getNarrative(productId);
  return {
    productId,
    name: catalog?.name ?? productId,
    experienceId,
    layoutKitId: narrative?.layoutKitId ?? "commerce",
    accent: accentVal,
    typography,
    sectionOrder,
    renderer: "experience",
    copy: {
      ...copy,
      story: copy.story ?? narrative?.story ?? [copy.body],
      scenario: copy.scenario ??
        narrative?.scenario ?? {
          title: copy.badge,
          body: copy.body,
          metrics: (copy.proofStats ?? []).map((p) => ({ label: p.label, value: p.value })),
        },
      antiConfusion: copy.antiConfusion ?? narrative?.antiConfusion ?? [],
      sectionTitles: {
        ...copy.sectionTitles,
        ...narrative?.sectionTitleOverrides,
      },
      notIncludes: copy.notIncludes.length ? copy.notIncludes : catalog?.notIncludes ?? [],
    },
    heroDemo: experienceId,
    pricing,
    interaction: { motions },
    loginHref,
  };
}

export const EXPERIENCE_MODULES: LandingProductModule[] = [
  mod(
    "catalogo-wa",
    "commerce-wa",
    tone("#0D9488", "#F0FDFA", "#0F766E", "cool"),
    ["hero", "trust", "surfaces", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Tienda web",
      title: "El cliente compra en tu vitrina.",
      titleAccent: "La venta entra al ERP.",
      body: "Ecommerce propio conectado al inventario y sucursales del ERP. Checkout con MercadoPago; WhatsApp queda como canal de consulta.",
      trust: ["Stock del ERP", "Checkout web", "Visible en Reportes"],
      sectionTitles: {
        surfaces: "Tres superficies, un pedido",
        flow: "Del browse al mensaje",
        proof: "Lo que mueve la venta",
        faq: "Antes de publicar",
        cta: "Publica tu vitrina hoy",
      },
      highlights: [
        {
          title: "Vitrina pública",
          body: "Link con categorías, foto y precio. El cliente entra sin login y ve qué hay.",
        },
        {
          title: "Carrito WA",
          body: "Un tap y el pedido llega a tu chat con ítems, cantidades y total.",
        },
        {
          title: "Stock real",
          body: "Cantidades del ERP. Evitas prometer lo que ya se vendió en mostrador.",
        },
        {
          title: "Cierre humano",
          body: "Tú confirmas pago, delivery y excepciones — el chat sigue siendo el canal.",
        },
      ],
      surfaces: [
        { label: "Vitrina", body: "Catálogo público con foto, precio y stock." },
        { label: "WhatsApp", body: "Mensaje armado con ítems y total." },
        { label: "Admin ERP", body: "Productos y reglas desde tu operación." },
      ],
      steps: [
        { n: "01", title: "Activa el slug", body: "URL pública de tu catálogo desde el ERP." },
        { n: "02", title: "Curá la vitrina", body: "Categorías y productos visibles al cliente." },
        { n: "03", title: "Cierra en chat", body: "Confirmas pago, zona y entrega como siempre." },
      ],
      proofStats: [
        { value: "1 tap", label: "Del carrito al WA" },
        { value: "ERP", label: "Fuente de stock" },
        { value: "0 app", label: "Sin instalar nada" },
      ],
      faqs: [
        {
          q: "¿Es una tienda online?",
          a: "Es vitrina + cierre por WhatsApp. Para checkout web con pasarela, usa Ecommerce.",
        },
        {
          q: "¿Sincroniza stock?",
          a: "Lee stock del ERP. Si tienes varios canales (Shopify, marketplace), Sync Stock es el producto de orquestación.",
        },
        {
          q: "¿Pagos en línea?",
          a: "El cobro lo cierras tú en el chat o con tu flujo habitual (Yape, transferencia, contraentrega).",
        },
        {
          q: "¿Sirve para mayoristas?",
          a: "No. Mayorista es B2B con listas y mínimos. Catálogo WA es retail consumidor por chat.",
        },
        {
          q: "¿El cliente necesita instalar algo?",
          a: "No. Abre el link en el navegador y manda el pedido por WhatsApp.",
        },
      ],
      notIncludes: ["checkout web", "pipeline CRM", "delivery on-demand", "listas B2B"],
    },
    plans(
      "Planes · Catálogo WA",
      "Para vender por chat sin fricción.",
      "Precios en soles. Escalas cuando la vitrina crece.",
      "cards-3",
      [
        {
          id: "vitrina",
          name: "Vitrina",
          price: 49,
          unit: "mes",
          description: "Una tienda, un número WA.",
          features: ["Slug público", "Carrito → WhatsApp", "Stock ERP"],
          cta: { label: "Empezar", href: "/login?mode=erp" },
        },
        {
          id: "comercio",
          name: "Comercio",
          price: 99,
          unit: "mes",
          description: "Más categorías y ritmo diario.",
          features: ["Todo lo anterior", "Más productos", "Soporte prioritario"],
          highlight: true,
          cta: { label: "Elegir Comercio", href: "/login?mode=erp" },
        },
        {
          id: "red",
          name: "Red",
          price: 179,
          unit: "mes",
          description: "Varias sedes o marcas.",
          features: ["Onboarding", "Multi-vitrina", "WhatsApp ventas"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=erp",
    ["lane-slide", "counter", "step-pulse"],
    { display: "sans-tight" },
  ),

  mod(
    "sync",
    "commerce-sync",
    tone("#0284C7", "#F0F9FF", "#0369A1", "cool"),
    ["hero", "trust", "integrations", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Sync Stock",
      title: "Un stock.",
      titleAccent: "Todos tus canales.",
      body: "Evita sobreventa unificando cantidades entre ERP, ecommerce y otros canales — mapeos y jobs auditable.",
      trust: ["Sin JOINs cruzados", "Jobs con historial", "Admin en ERP"],
      sectionTitles: {
        integrations: "Canales que habla Sync",
        flow: "Cómo corre un job",
        proof: "Control operativo",
        faq: "Integración sin drama",
        cta: "Ordena tu stock omnicanal",
      },
      highlights: [
        { title: "Canales mapeados", body: "SKU origen → destino por canal." },
        { title: "Jobs", body: "Pull, push o reconcile con log." },
        { title: "Admin claro", body: "Operas desde el ERP." },
      ],
      integrations: [
        { name: "ERP", role: "Fuente maestra de cantidad" },
        { name: "Ecommerce", role: "Canal de vitrina online" },
        { name: "Marketplace", role: "Mapeo por SKU externo" },
      ],
      steps: [
        { n: "01", title: "Conecta", body: "Canales y credenciales." },
        { n: "02", title: "Mapea", body: "SKU a SKU sin ambigüedad." },
        { n: "03", title: "Reconciliá", body: "Jobs cuando el stock se mueve." },
      ],
      proofStats: [
        { value: "3+", label: "Canales tipicos" },
        { value: "log", label: "Cada job auditado" },
        { value: "0 UI", label: "Sin tienda propia" },
      ],
      faqs: [
        { q: "¿Mueve el master?", a: "El maestro vive en ERP/Ecommerce; Sync orquesta." },
        { q: "¿Necesito UI de tienda?", a: "No. Sync es operación admin." },
        { q: "¿Cross-database?", a: "No. Integración por API/IDs." },
      ],
      notIncludes: ["UI de tienda", "pipeline CRM"],
    },
    plans(
      "Planes · Sync",
      "Capacidad por canales sincronizados.",
      "Paga según cuántos canales mantienes al día.",
      "tier-list",
      [
        {
          id: "canal",
          name: "Canal",
          price: 49,
          unit: "mes",
          description: "Un canal secundario.",
          features: ["1 canal", "Jobs diarios", "Log básico"],
          cta: { label: "Empezar", href: "/login?mode=erp" },
        },
        {
          id: "omni",
          name: "Omni",
          price: 99,
          unit: "mes",
          description: "Varios canales activos.",
          features: ["Hasta 4 canales", "Reconcile", "Alertas"],
          highlight: true,
          cta: { label: "Elegir Omni", href: "/login?mode=erp" },
        },
        {
          id: "red",
          name: "Red",
          price: 179,
          unit: "mes",
          description: "Red de puntos y marketplaces.",
          features: ["Canales ampliados", "Onboarding", "Prioridad"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=erp",
    ["progress-fill", "counter", "step-pulse"],
    { display: "mono-num" },
  ),

  mod(
    "mayorista",
    "commerce-b2b",
    tone("#B45309", "#FFFBEB", "#92400E", "warm"),
    ["hero", "trust", "job", "flow", "notFor", "pricing", "faq", "cta"],
    {
      badge: "Mayorista B2B",
      title: "Precios por volumen.",
      titleAccent: "Pedidos de reventa.",
      body: "Listas, mínimos y portal para clientes B2B — separado del mostrador retail.",
      trust: ["Listas por cliente", "Mínimos de compra", "Portal B2B"],
      sectionTitles: {
        job: "Hecho para reventa",
        flow: "Del catálogo al pedido B2B",
        notFor: "Esto no es…",
        faq: "Mayorista sin mezclar retail",
        cta: "Abre tu portal B2B",
      },
      highlights: [
        { title: "Listas", body: "Precios distintos por cuenta." },
        { title: "Mínimos", body: "Reglas de cantidad por ítem." },
        { title: "Portal", body: "El cliente pide sin pasar por POS." },
      ],
      audience: [
        { title: "Distribuidores", body: "Cuentas con precio negociado." },
        { title: "Almacenes", body: "Pedidos recurrentes por semana." },
      ],
      steps: [
        { n: "01", title: "Cuentas", body: "Alta de clientes B2B." },
        { n: "02", title: "Listas", body: "Asigna precios y mínimos." },
        { n: "03", title: "Pedidos", body: "Portal o carga interna." },
      ],
      faqs: [
        { q: "¿Sirve como POS?", a: "No. El mostrador es Pocket/ERP." },
        { q: "¿Es Catálogo WA?", a: "No. WA es retail por chat; Mayorista es B2B." },
        { q: "¿Facturación?", a: "El documento lo cierra tu ERP/SUNAT según tu flujo." },
      ],
      notIncludes: ["POS retail", "catálogo WhatsApp consumidor", "matching delivery"],
    },
    plans(
      "Planes · Mayorista",
      "Según el tamaño de tu red B2B.",
      "Listas y portal sin ensuciar el retail.",
      "cards-3",
      [
        {
          id: "lista",
          name: "Lista",
          price: 79,
          unit: "mes",
          description: "Pocas cuentas clave.",
          features: ["Listas de precio", "Mínimos", "Pedidos internos"],
          cta: { label: "Empezar", href: "/login?mode=mayorista" },
        },
        {
          id: "portal",
          name: "Portal",
          price: 149,
          unit: "mes",
          description: "Clientes pidiendo solos.",
          features: ["Portal B2B", "Cuentas ampliadas", "Historial"],
          highlight: true,
          cta: { label: "Elegir Portal", href: "/login?mode=mayorista" },
        },
        {
          id: "red",
          name: "Red",
          price: 249,
          unit: "mes",
          description: "Distribución multi-zona.",
          features: ["Onboarding", "Soporte", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=mayorista",
    ["lane-slide", "step-pulse", "counter"],
    { display: "sans-tight" },
  ),

  mod(
    "taller",
    "plant-taller",
    tone("#EA580C", "#FFF7ED", "#C2410C", "warm"),
    ["hero", "trust", "surfaces", "flow", "proof", "includes", "pricing", "faq", "cta"],
    {
      badge: "Taller",
      title: "Órdenes de producción.",
      titleAccent: "Insumos y avance.",
      body: "OT de taller: materiales, estados y entrega — distinto del mantenimiento preventivo de planta.",
      trust: ["OT de producción", "Insumos", "Estados claros"],
      sectionTitles: {
        surfaces: "Quién toca la OT",
        flow: "De la orden al cierre",
        proof: "Ritmo de planta",
        includes: "En la caja del taller",
        faq: "Taller vs mantto",
        cta: "Pon tu planta en marcha",
      },
      highlights: [
        { title: "OT producción", body: "Trabajos con insumos y avance." },
        { title: "Estados", body: "Abierta → en proceso → lista." },
        { title: "Planta", body: "Vista admin y técnico." },
      ],
      surfaces: [
        { label: "Admin planta", body: "Crea OT, asigna y prioriza." },
        { label: "Técnico", body: "Marca avance e insumos usados." },
      ],
      steps: [
        { n: "01", title: "Abre OT", body: "Producto, insumos, plazo." },
        { n: "02", title: "Produce", body: "El técnico registra avance." },
        { n: "03", title: "Cierra", body: "Entrega y trazabilidad." },
      ],
      proofStats: [
        { value: "OT", label: "Por trabajo" },
        { value: "3+", label: "Estados visibles" },
        { value: "2 UI", label: "Admin + técnico" },
      ],
      faqs: [
        { q: "¿Es mantenimiento?", a: "No. Mantto es preventivo de activos; Taller es producción." },
        { q: "¿WMS?", a: "WMS mueve stock de almacén; Taller ejecuta OT." },
        { q: "¿ERP?", a: "Producto con BD/superficie propia de planta." },
      ],
      notIncludes: ["rutas de delivery", "pipeline CRM", "preventivo de activos"],
    },
    plans(
      "Planes · Taller",
      "Según el tamaño de tu planta.",
      "Pensado para OT, no para tickets genéricos.",
      "cards-3",
      [
        {
          id: "taller",
          name: "Taller",
          price: 69,
          unit: "mes",
          description: "Un equipo chico.",
          features: ["OT producción", "Insumos", "2 usuarios"],
          cta: { label: "Empezar", href: "/login?mode=erp" },
        },
        {
          id: "planta",
          name: "Planta",
          price: 129,
          unit: "mes",
          description: "Varias líneas.",
          features: ["Más OT", "Roles", "Reportes"],
          highlight: true,
          cta: { label: "Elegir Planta", href: "/login?mode=erp" },
        },
        {
          id: "red",
          name: "Red",
          price: 219,
          unit: "mes",
          description: "Varias sedes.",
          features: ["Onboarding", "Prioridad", "Multi-planta"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=erp",
    ["progress-fill", "step-pulse", "counter"],
    { display: "sans-tight" },
  ),

  mod(
    "preventa",
    "preorder",
    tone("#E11D48", "#FFF1F2", "#BE123C", "warm"),
    ["hero", "trust", "proof", "flow", "includes", "pricing", "faq", "cta"],
    {
      badge: "Preventa",
      title: "Reserva la edición.",
      titleAccent: "Cobra el anticipo.",
      body: "Campañas con cupo, anticipo y reservas públicas — ideal para colecciones limitadas.",
      trust: ["Cupos visibles", "% de anticipo", "Vitrina pública"],
      sectionTitles: {
        proof: "La edición se agota",
        flow: "De la campaña a la reserva",
        includes: "Qué trae Preventa",
        faq: "Antes del drop",
        cta: "Lanza tu próxima edición",
      },
      highlights: [
        { title: "Cupos", body: "El cliente ve lo que queda." },
        { title: "Anticipo", body: "Defines el % por campaña." },
        { title: "Estado de pago", body: "Pendiente/pagado en MVP." },
      ],
      steps: [
        { n: "01", title: "Campaña", body: "Slug y % de anticipo." },
        { n: "02", title: "Ítems", body: "SKU, precio y cupo." },
        { n: "03", title: "Vitrina", body: "/preventa/{slug}." },
      ],
      proofStats: [
        { value: "cupo", label: "Restante en vivo" },
        { value: "%", label: "Anticipo configurable" },
        { value: "slug", label: "Link compartible" },
      ],
      faqs: [
        { q: "¿Es Ecommerce?", a: "Complementa. Preventa es reserva + anticipo de edición." },
        { q: "¿Mercado Pago?", a: "Estado de pago en MVP; cobro online se diseña aparte." },
        { q: "¿B2B?", a: "No. Para eso está Mayorista." },
      ],
      notIncludes: ["pedido B2B", "delivery on-demand"],
    },
    plans(
      "Planes · Preventa",
      "Según el ritmo de tus drops.",
      "Cupos y anticipos sin ensuciar la tienda permanente.",
      "usage-meter",
      [
        {
          id: "drop",
          name: "Drop",
          price: 59,
          unit: "mes",
          description: "Una campaña a la vez.",
          features: ["1 campaña activa", "Cupos", "Anticipo %"],
          cta: { label: "Empezar", href: "/login?mode=ecommerce" },
        },
        {
          id: "coleccion",
          name: "Colección",
          price: 109,
          unit: "mes",
          description: "Varios drops al mes.",
          features: ["Campañas paralelas", "Más ítems", "Estados de pago"],
          highlight: true,
          cta: { label: "Elegir Colección", href: "/login?mode=ecommerce" },
        },
        {
          id: "marca",
          name: "Marca",
          price: 189,
          unit: "mes",
          description: "Calendario de ediciones.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=ecommerce",
    ["counter", "progress-fill", "step-pulse"],
    { display: "sans-tight" },
  ),

  mod(
    "crm",
    "pipeline-crm",
    tone("#2563EB", "#EFF6FF", "#1D4ED8", "paper"),
    ["hero", "trust", "job", "flow", "integrations", "pricing", "faq", "cta"],
    {
      badge: "CRM",
      title: "Pipeline que se mueve.",
      titleAccent: "Sin mezclar el master.",
      body: "Deals, etapas y actividades. El cliente ERP va por ID — el CRM no reemplaza tu padrón.",
      trust: ["Etapas propias", "Actividades", "Sin IA forzada"],
      sectionTitles: {
        job: "Comercial, no padrones",
        flow: "Cómo avanza un deal",
        integrations: "Enlace con el ERP",
        faq: "CRM con límites claros",
        cta: "Mueve tu pipeline",
      },
      highlights: [
        { title: "Pipeline", body: "Etapas que tú defines." },
        { title: "Actividades", body: "Notas y seguimiento." },
        { title: "Cliente por ID", body: "Referencia al ERP, no duplicado." },
      ],
      integrations: [
        { name: "ERP", role: "Cliente / cuenta por ID" },
        { name: "Equipo comercial", role: "Deals y actividades" },
      ],
      steps: [
        { n: "01", title: "Etapas", body: "Diseña el embudo." },
        { n: "02", title: "Deals", body: "Arrastra y actualiza." },
        { n: "03", title: "Cierra", body: "Ganado / perdido con historial." },
      ],
      faqs: [
        { q: "¿Reemplaza clientes ERP?", a: "No. Referencia por ID." },
        { q: "¿Recluta?", a: "Recluta es vacantes y candidatos." },
        { q: "¿IA?", a: "Reglas simples; sin copiloto obligatorio." },
      ],
      notIncludes: ["padrón de clientes", "reclutamiento", "POS"],
    },
    plans(
      "Planes · CRM",
      "Para el equipo que cierra tratos.",
      "Pipeline claro, sin teatro de “AI CRM”.",
      "cards-3",
      [
        {
          id: "pipeline",
          name: "Pipeline",
          price: 69,
          unit: "mes",
          description: "Un equipo chico.",
          features: ["Etapas", "Deals", "Actividades"],
          cta: { label: "Empezar", href: "/login?mode=crm" },
        },
        {
          id: "equipo",
          name: "Equipo",
          price: 129,
          unit: "mes",
          description: "Más seats y ritmo.",
          features: ["Más usuarios", "Historial", "Reportes"],
          highlight: true,
          cta: { label: "Elegir Equipo", href: "/login?mode=crm" },
        },
        {
          id: "org",
          name: "Org",
          price: 219,
          unit: "mes",
          description: "Varias mesas comerciales.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=crm",
    ["lane-slide", "step-pulse", "counter"],
    { display: "sans-tight" },
  ),

  mod(
    "envios",
    "ship-track",
    tone("#0891B2", "#ECFEFF", "#0E7490", "cool"),
    ["hero", "trust", "flow", "proof", "integrations", "pricing", "faq", "cta"],
    {
      badge: "Envíos",
      title: "Guía con timeline.",
      titleAccent: "Eventos que se ven.",
      body: "Crea guías, registra hitos y comparte tracking — sin confundirlo con delivery on-demand.",
      trust: ["Guías", "Eventos", "Tracking público"],
      sectionTitles: {
        flow: "De la guía al destinatario",
        proof: "Visibilidad del envío",
        integrations: "Con qué se conecta",
        faq: "Envíos vs delivery",
        cta: "Empieza a rastrear",
      },
      highlights: [
        { title: "Guías", body: "Número y destinatario." },
        { title: "Timeline", body: "Eventos con marca de tiempo." },
        { title: "Público", body: "Link de tracking." },
      ],
      integrations: [
        { name: "ERP / pedidos", role: "Origen del envío" },
        { name: "Tracking", role: "Página pública por guía" },
      ],
      steps: [
        { n: "01", title: "Crea guía", body: "Destino y referencia." },
        { n: "02", title: "Eventos", body: "Recolectado, en tránsito, entregado." },
        { n: "03", title: "Comparte", body: "Link al cliente." },
      ],
      proofStats: [
        { value: "guía", label: "Por envío" },
        { value: "live", label: "Timeline visible" },
        { value: "link", label: "Tracking público" },
      ],
      faqs: [
        { q: "¿Es Delivery?", a: "No. Delivery es encargo on-demand con repartidor." },
        { q: "¿Flotas?", a: "Flotas administra vehículos; Envíos es la guía." },
        { q: "¿Couriers?", a: "Puedes registrar eventos aunque el courier sea externo." },
      ],
      notIncludes: ["matching de repartidores", "solicitudes taxi"],
    },
    plans(
      "Planes · Envíos",
      "Según el volumen de guías.",
      "Tracking claro para tu operación de salida.",
      "cards-3",
      [
        {
          id: "guia",
          name: "Guía",
          price: 59,
          unit: "mes",
          description: "Volumen chico.",
          features: ["Guías", "Timeline", "Link público"],
          cta: { label: "Empezar", href: "/login?mode=envios" },
        },
        {
          id: "salida",
          name: "Salida",
          price: 119,
          unit: "mes",
          description: "Operación diaria.",
          features: ["Más guías", "Eventos", "Admin"],
          highlight: true,
          cta: { label: "Elegir Salida", href: "/login?mode=envios" },
        },
        {
          id: "red",
          name: "Red",
          price: 199,
          unit: "mes",
          description: "Varios orígenes.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=envios",
    ["step-pulse", "path-draw", "counter"],
    { display: "sans-tight" },
  ),

  mod(
    "wms",
    "ops-wms",
    tone("#4F46E5", "#EEF2FF", "#3730A3", "paper"),
    ["hero", "trust", "surfaces", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "WMS",
      title: "Picking y ubicación.",
      titleAccent: "Almacén que se mueve.",
      body: "Tareas de almacén: recepción, ubicación y picking — distinto de rutas de despacho en calle.",
      trust: ["Ubicaciones", "Picking", "Operario + admin"],
      sectionTitles: {
        surfaces: "Piso y torre",
        flow: "Flujo de almacén",
        proof: "Ritmo de olas",
        faq: "WMS vs despacho",
        cta: "Ordena tu almacén",
      },
      highlights: [
        { title: "Ubicaciones", body: "Dónde vive cada SKU." },
        { title: "Picking", body: "Tareas por ola." },
        { title: "Recepción", body: "Entrada a stock." },
      ],
      surfaces: [
        { label: "Admin WMS", body: "Olas, reglas y prioridades." },
        { label: "Operario", body: "Tareas en piso, una a una." },
      ],
      steps: [
        { n: "01", title: "Recibe", body: "Ingreso a ubicación." },
        { n: "02", title: "Pick", body: "Lista de tareas." },
        { n: "03", title: "Libera", body: "Listo para despacho." },
      ],
      proofStats: [
        { value: "ola", label: "De picking" },
        { value: "bin", label: "Ubicación" },
        { value: "2 UI", label: "Admin + operario" },
      ],
      faqs: [
        { q: "¿Es Despacho?", a: "Despacho es ruta en calle; WMS es almacén." },
        { q: "¿Inventario ERP?", a: "WMS opera tareas; el master puede vivir en ERP." },
        { q: "¿Delivery?", a: "No. No asigna repartidores." },
      ],
      notIncludes: ["rutas de calle", "matching taxis"],
    },
    plans(
      "Planes · WMS",
      "Según el tamaño de tu piso.",
      "Tareas de almacén, no GPS de calle.",
      "cards-3",
      [
        {
          id: "piso",
          name: "Piso",
          price: 89,
          unit: "mes",
          description: "Un almacén.",
          features: ["Picking", "Ubicaciones", "Operario"],
          cta: { label: "Empezar", href: "/login?mode=wms" },
        },
        {
          id: "ola",
          name: "Ola",
          price: 159,
          unit: "mes",
          description: "Más volumen diario.",
          features: ["Olas", "Roles", "Historial"],
          highlight: true,
          cta: { label: "Elegir Ola", href: "/login?mode=wms" },
        },
        {
          id: "red",
          name: "Red",
          price: 259,
          unit: "mes",
          description: "Varios almacenes.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=wms",
    ["lane-slide", "step-pulse", "progress-fill"],
    { display: "sans-tight" },
  ),

  mod(
    "despacho",
    "ops-board",
    tone("#16A34A", "#F0FDF4", "#15803D", "paper"),
    ["hero", "trust", "flow", "proof", "notFor", "pricing", "faq", "cta"],
    {
      badge: "Despacho",
      title: "Paradas del día.",
      titleAccent: "Ruta que se cumple.",
      body: "Arma rutas, asigna paradas y cierra entregas de distribución — no es flota ni taxi.",
      trust: ["Rutas", "Paradas", "Cierre de visita"],
      sectionTitles: {
        flow: "Cómo corre la ruta",
        proof: "Salida del día",
        notFor: "Esto no es…",
        faq: "Despacho con límites",
        cta: "Arma la ruta de hoy",
      },
      highlights: [
        { title: "Rutas", body: "Secuencia de paradas." },
        { title: "Asignación", body: "Chofer / unidad." },
        { title: "Cierre", body: "Entregado o incidencia." },
      ],
      steps: [
        { n: "01", title: "Arma", body: "Paradas del día." },
        { n: "02", title: "Sale", body: "Chofer en ruta." },
        { n: "03", title: "Cierra", body: "Cada visita con estado." },
      ],
      proofStats: [
        { value: "ruta", label: "Por día" },
        { value: "stop", label: "Paradas ordenadas" },
        { value: "ok", label: "Cierre por visita" },
      ],
      faqs: [
        { q: "¿Es Flotas?", a: "Flotas administra vehículos y papeles; Despacho opera la ruta." },
        { q: "¿Taxi?", a: "Taxi es solicitud de pasajeros on-demand." },
        { q: "¿WMS?", a: "WMS prepara en almacén; Despacho sale a calle." },
      ],
      notIncludes: ["matching taxis", "admin de SOAT", "picking de almacén"],
    },
    plans(
      "Planes · Despacho",
      "Según cuántas rutas sales.",
      "Distribución del día, sin marketplace.",
      "cards-3",
      [
        {
          id: "ruta",
          name: "Ruta",
          price: 69,
          unit: "mes",
          description: "Pocas salidas.",
          features: ["Rutas", "Paradas", "Cierre"],
          cta: { label: "Empezar", href: "/login?mode=erp" },
        },
        {
          id: "flota",
          name: "Ciudad",
          price: 129,
          unit: "mes",
          description: "Varias rutas diarias.",
          features: ["Más rutas", "Asignación", "Historial"],
          highlight: true,
          cta: { label: "Elegir Ciudad", href: "/login?mode=erp" },
        },
        {
          id: "red",
          name: "Red",
          price: 209,
          unit: "mes",
          description: "Multi-zona.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=erp",
    ["lane-slide", "step-pulse", "pin-drop"],
    { display: "sans-tight" },
  ),

  mod(
    "taxi",
    "mobility-taxi",
    tone("#CA8A04", "#FEFCE8", "#A16207", "warm"),
    ["hero", "trust", "surfaces", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Taxi",
      title: "Solicitud.",
      titleAccent: "Conductor. Tracking.",
      body: "Operación de taxis con base propia: pasajero pide, conductor acepta, admin controla.",
      trust: ["Tres superficies", "Viajes con estado", "BD propia"],
      sectionTitles: {
        surfaces: "Quién usa Taxi",
        flow: "Del pedido al cierre",
        proof: "Operación en minutos",
        faq: "Taxi con límites claros",
        cta: "Enciende tu operación",
      },
      highlights: [
        { title: "Pasajero", body: "Pide y ve asignación." },
        { title: "Conductor", body: "Acepta y cierra viaje." },
        { title: "Admin", body: "Controla la base." },
      ],
      surfaces: [
        { label: "Admin", body: "Operadores, viajes, reglas." },
        { label: "Pasajero", body: "Solicitud y tracking." },
        { label: "Conductor", body: "Aceptar y completar." },
      ],
      steps: [
        { n: "01", title: "Bootstrap", body: "Slug de operación." },
        { n: "02", title: "Conductores", body: "Alta con acceso." },
        { n: "03", title: "Viajes", body: "Asignación y cierre." },
      ],
      proofStats: [
        { value: "3 UI", label: "Admin · pax · driver" },
        { value: "live", label: "Estados de viaje" },
        { value: "db", label: "db_taxi aislada" },
      ],
      faqs: [
        { q: "¿Sirve para delivery?", a: "No. Delivery es encargos; Taxi es pasajeros." },
        { q: "¿Flotas?", a: "Flotas administra vehículos de empresa." },
        { q: "¿ERP?", a: "Totalmente separado." },
      ],
      notIncludes: ["encargos de paquetes", "flota corporativa"],
    },
    plans(
      "Planes · Taxi",
      "Por tamaño de operación.",
      "Pensado para operadores, no un solo freelance.",
      "cards-3",
      [
        {
          id: "flota-chica",
          name: "Flota chica",
          price: 149,
          unit: "mes",
          description: "Operación barrial.",
          features: ["Admin + apps", "Conductores", "Tracking básico"],
          cta: { label: "Empezar", href: "/login?mode=taxi" },
        },
        {
          id: "ciudad",
          name: "Ciudad",
          price: 279,
          unit: "mes",
          description: "Varias zonas.",
          features: ["Más volumen", "Reglas", "Soporte"],
          highlight: true,
          cta: { label: "Elegir Ciudad", href: "/login?mode=taxi" },
        },
        {
          id: "red",
          name: "Red",
          price: 449,
          unit: "mes",
          description: "Multi-ciudad.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=taxi",
    ["path-draw", "pin-drop", "step-pulse"],
    { display: "sans-tight" },
  ),

  mod(
    "delivery",
    "mobility-delivery",
    tone("#F97316", "#FFEDD5", "#EA580C", "ink"),
    ["hero", "trust", "surfaces", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Delivery",
      title: "Encargo en ruta.",
      titleAccent: "Repartidor asignado.",
      body: "Pedidos de paquete/comida con repartidor — no es taxi de pasajeros ni guía courier larga.",
      trust: ["Cliente", "Repartidor", "Admin"],
      sectionTitles: {
        surfaces: "Quién mueve el encargo",
        flow: "Del pedido a la puerta",
        proof: "En minutos, no en días",
        faq: "Delivery vs envíos",
        cta: "Activa tu zona",
      },
      highlights: [
        { title: "Pedido", body: "Cliente solicita encargo." },
        { title: "Asignación", body: "Repartidor en ruta." },
        { title: "Cierre", body: "Entrega confirmada." },
      ],
      surfaces: [
        { label: "Cliente", body: "Pide y sigue el encargo." },
        { label: "Repartidor", body: "Acepta y entrega." },
        { label: "Admin", body: "Zonas y operación." },
      ],
      steps: [
        { n: "01", title: "Zona", body: "Cobertura de delivery." },
        { n: "02", title: "Pedido", body: "Cliente solicita." },
        { n: "03", title: "Entrega", body: "Repartidor cierra." },
      ],
      proofStats: [
        { value: "zona", label: "Cobertura" },
        { value: "ETA", label: "En ruta" },
        { value: "3 UI", label: "Roles claros" },
      ],
      faqs: [
        { q: "¿Es Taxi?", a: "No. Taxi mueve personas." },
        { q: "¿Envíos?", a: "Envíos es guía/timeline; Delivery es on-demand." },
        { q: "¿Flotas?", a: "Flotas administra activos; aquí asignas repartidores." },
      ],
      notIncludes: ["viajes de pasajeros", "guías courier largas"],
    },
    plans(
      "Planes · Delivery",
      "Según tu cobertura.",
      "On-demand de encargos, no de pasajeros.",
      "cards-3",
      [
        {
          id: "zona",
          name: "Zona",
          price: 129,
          unit: "mes",
          description: "Una zona.",
          features: ["Admin + apps", "Repartidores", "Pedidos"],
          cta: { label: "Empezar", href: "/login?mode=delivery" },
        },
        {
          id: "ciudad",
          name: "Ciudad",
          price: 249,
          unit: "mes",
          description: "Varias zonas.",
          features: ["Más volumen", "Reglas", "Soporte"],
          highlight: true,
          cta: { label: "Elegir Ciudad", href: "/login?mode=delivery" },
        },
        {
          id: "red",
          name: "Red",
          price: 399,
          unit: "mes",
          description: "Multi-ciudad.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=delivery",
    ["path-draw", "counter", "step-pulse"],
    { display: "sans-tight" },
  ),

  mod(
    "flotas",
    "ops-fleet",
    tone("#475569", "#F1F5F9", "#334155", "ink"),
    ["hero", "trust", "job", "integrations", "proof", "pricing", "faq", "cta"],
    {
      badge: "Flotas",
      title: "Vehículos.",
      titleAccent: "Papeles y combustible.",
      body: "Administra la flota de empresa: placa, SOAT, conductores y cargas — integra por API a Taxi/Delivery/Despacho.",
      trust: ["Placas", "Vencimientos", "Combustible"],
      sectionTitles: {
        job: "Activos, no matching",
        integrations: "Quién consume la flota",
        proof: "Control del patio",
        faq: "Flotas con límites",
        cta: "Ordena tu patio",
      },
      highlights: [
        { title: "Vehículos", body: "Placa, marca, docs." },
        { title: "Conductores", body: "Licencia y acceso." },
        { title: "Combustible", body: "Registros por fecha." },
      ],
      integrations: [
        { name: "Taxi / Delivery", role: "Unidades disponibles vía API" },
        { name: "Despacho", role: "Asignación de ruta" },
      ],
      steps: [
        { n: "01", title: "Alta", body: "Slug de empresa." },
        { n: "02", title: "Unidades", body: "Placas y docs." },
        { n: "03", title: "Opera", body: "Combustible y asignación." },
      ],
      proofStats: [
        { value: "placa", label: "Por unidad" },
        { value: "SOAT", label: "Vencimientos" },
        { value: "L", label: "Combustible" },
      ],
      faqs: [
        { q: "¿Hace matching?", a: "No. Eso es Taxi/Delivery." },
        { q: "¿Rutas del día?", a: "Despacho opera rutas; Flotas administra activos." },
        { q: "¿ERP?", a: "BD propia db_flotas." },
      ],
      notIncludes: ["matching marketplace Taxi/Delivery"],
    },
    plans(
      "Planes · Flotas",
      "Según el tamaño de tu patio.",
      "Docs y combustible, no marketplace.",
      "tier-list",
      [
        {
          id: "unidad",
          name: "Unidad",
          price: 99,
          unit: "mes",
          description: "Pocas unidades.",
          features: ["Vehículos", "Docs", "Combustible"],
          cta: { label: "Empezar", href: "/login?mode=flotas" },
        },
        {
          id: "empresa",
          name: "Empresa",
          price: 189,
          unit: "mes",
          description: "Flota mediana.",
          features: ["Más unidades", "Conductores", "Alertas"],
          highlight: true,
          cta: { label: "Elegir Empresa", href: "/login?mode=flotas" },
        },
        {
          id: "grupo",
          name: "Grupo",
          price: 299,
          unit: "mes",
          description: "Multi-empresa.",
          features: ["Onboarding", "Prioridad", "API"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=flotas",
    ["counter", "step-pulse", "progress-fill"],
    { display: "mono-num" },
  ),

  mod(
    "campo",
    "ops-field",
    tone("#65A30D", "#F7FEE7", "#4D7C0F", "paper"),
    ["hero", "trust", "flow", "proof", "includes", "pricing", "faq", "cta"],
    {
      badge: "Campo",
      title: "Check-in en la visita.",
      titleAccent: "GPS que cuenta.",
      body: "Vendedores en calle con ruta del día, check-in GPS y evidencias. El supervisor ve quién llegó — sin convertir Campo en un CRM de deals ni en un WMS.",
      trust: ["Ruta del día", "Check-in GPS", "Nota / foto", "Vista supervisor"],
      sectionTitles: {
        flow: "La jornada en campo",
        proof: "Lo que el supervisor ve",
        includes: "Qué incluye Campo",
        faq: "Campo vs CRM (y el resto)",
        cta: "Saca al equipo a calle",
        story: "La calle, no el embudo",
        scenario: "Un martes en Lima Este",
        antiConfusion: "Campo no es…",
      },
      highlights: [
        {
          title: "Ruta del día",
          body: "Lista de clientes a visitar, ordenada antes de salir. Sin armar el día en un chat.",
        },
        {
          title: "Check-in GPS",
          body: "Al llegar, el vendedor marca el pin. Queda hora y ubicación como evidencia.",
        },
        {
          title: "Cierre con nota",
          body: "Texto o foto de la visita. El jefe no depende del ‘ya voy’ eterno.",
        },
      ],
      steps: [
        {
          n: "01",
          title: "Planifica",
          body: "Cargas la ruta: clientes, zona y orden del día.",
        },
        {
          n: "02",
          title: "Check-in",
          body: "En el punto, el vendedor confirma llegada con GPS.",
        },
        {
          n: "03",
          title: "Cierra",
          body: "Deja resultado, nota o foto. El tablero se actualiza.",
        },
      ],
      proofStats: [
        { value: "GPS", label: "Check-in real" },
        { value: "día", label: "Ruta visible" },
        { value: "ok", label: "Cierre de visita" },
      ],
      faqs: [
        {
          q: "¿Es CRM?",
          a: "No. CRM es pipeline de deals y etapas. Campo es presencia en calle: ruta, check-in y evidencia de visita.",
        },
        {
          q: "¿Sirve para delivery de paquetes?",
          a: "No. Eso es Delivery (encargo on-demand) o Despacho (ruta de mercancía). Campo es visita comercial.",
        },
        {
          q: "¿Funciona offline?",
          a: "El MVP es online. Offline con cola de sync se diseña aparte; no lo prometemos aquí.",
        },
        {
          q: "¿El cliente final instala algo?",
          a: "No. Opera tu equipo (vendedor + admin). El mapa es para tu operación, no una app del cliente.",
        },
      ],
      notIncludes: [
        "pipeline de deals / CRM",
        "matching de repartidores",
        "picking WMS",
        "app del cliente final",
      ],
    },
    plans(
      "Planes · Campo",
      "Según el tamaño del equipo en calle.",
      "Pagas por operación de visitas con evidencia — no por ‘asientos de CRM’ genéricos.",
      "cards-3",
      [
        {
          id: "ruta",
          name: "Ruta",
          price: 79,
          unit: "mes",
          description: "Hasta un equipo chico en una zona.",
          features: [
            "Rutas del día",
            "Check-in GPS",
            "Admin supervisor",
            "Historial básico de visitas",
          ],
          cta: { label: "Empezar", href: "/login?mode=campo" },
        },
        {
          id: "equipo",
          name: "Equipo",
          price: 149,
          unit: "mes",
          description: "Equipo regional con más ritmo.",
          features: [
            "Más vendedores",
            "Evidencias (nota/foto)",
            "Tablero a mediodía",
            "Reportes de cobertura",
          ],
          highlight: true,
          cta: { label: "Elegir Equipo", href: "/login?mode=campo" },
        },
        {
          id: "red",
          name: "Red",
          price: 239,
          unit: "mes",
          description: "Varias zonas o sedes.",
          features: [
            "Multi-zona",
            "Onboarding guiado",
            "Soporte prioritario",
            "Escala con tu fuerza de ventas",
          ],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=campo",
    ["pin-drop", "counter", "step-pulse"],
    { display: "sans-tight" },
  ),

  mod(
    "academia",
    "learn-path",
    tone("#7C3AED", "#F5F3FF", "#6D28D9", "paper"),
    ["hero", "trust", "surfaces", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Academia",
      title: "Ruta de aprendizaje.",
      titleAccent: "Progreso visible.",
      body: "Cursos, módulos y avance de alumnos — para capacitar equipos o clientes, no para CRM.",
      trust: ["Módulos", "Progreso", "Admin + alumno"],
      sectionTitles: {
        surfaces: "Quién aprende y quién publica",
        flow: "De módulo a certificado de avance",
        proof: "Aprendizaje medible",
        faq: "Academia con límites",
        cta: "Abre tu aula",
      },
      highlights: [
        { title: "Ruta", body: "Módulos en orden." },
        { title: "Progreso", body: "% por alumno." },
        { title: "Admin", body: "Publicas y das de alta." },
      ],
      surfaces: [
        { label: "Admin", body: "Cursos, módulos, alumnos." },
        { label: "Alumno", body: "Ruta y progreso." },
      ],
      steps: [
        { n: "01", title: "Publica", body: "Curso y módulos." },
        { n: "02", title: "Invita", body: "Alumnos al aula." },
        { n: "03", title: "Mide", body: "Avance por módulo." },
      ],
      proofStats: [
        { value: "%", label: "Progreso" },
        { value: "mod", label: "Por ruta" },
        { value: "2 UI", label: "Admin + alumno" },
      ],
      faqs: [
        { q: "¿Es LMS enorme?", a: "MVP enfocado a rutas claras, no SCORM legacy." },
        { q: "¿CRM?", a: "No. Capacitación, no pipeline." },
        { q: "¿Certificados PDF?", a: "Progreso sí; certificados fancy se diseñan aparte." },
      ],
      notIncludes: ["pipeline comercial", "expediente clínico"],
    },
    plans(
      "Planes · Academia",
      "Según alumnos y cursos.",
      "Rutas claras para capacitar de verdad.",
      "cards-3",
      [
        {
          id: "aula",
          name: "Aula",
          price: 79,
          unit: "mes",
          description: "Un curso activo.",
          features: ["Módulos", "Progreso", "Admin"],
          cta: { label: "Empezar", href: "/login?mode=academia" },
        },
        {
          id: "equipos",
          name: "Equipos",
          price: 149,
          unit: "mes",
          description: "Varios cursos.",
          features: ["Más alumnos", "Rutas", "Reportes"],
          highlight: true,
          cta: { label: "Elegir Equipos", href: "/login?mode=academia" },
        },
        {
          id: "partner",
          name: "Partner",
          price: 249,
          unit: "mes",
          description: "Formación a escala.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=academia",
    ["progress-fill", "step-pulse", "counter"],
    { display: "serif" },
  ),

  mod(
    "agenda",
    "book-slot",
    tone("#14B8A6", "#CCFBF1", "#0F766E", "cool"),
    ["hero", "trust", "flow", "proof", "notFor", "pricing", "faq", "cta"],
    {
      badge: "Agenda",
      title: "Elige el horario.",
      titleAccent: "Reserva 1-a-1.",
      body: "Slots del profesional, reserva pública y estado de pago — sin expediente clínico.",
      trust: ["Slots", "Reserva pública", "Pago flag"],
      sectionTitles: {
        flow: "Cómo se reserva",
        proof: "Horarios que se llenan",
        notFor: "Esto no es…",
        faq: "Agenda con límites",
        cta: "Publica tus horarios",
      },
      highlights: [
        { title: "Slots", body: "Inicio, duración, precio." },
        { title: "Público", body: "/agenda/{slug}." },
        { title: "Pago", body: "Pendiente/pagado en MVP." },
      ],
      steps: [
        { n: "01", title: "Horarios", body: "Disponibilidad semanal." },
        { n: "02", title: "Reserva", body: "Cliente elige slot." },
        { n: "03", title: "Confirmas", body: "Estado de pago en admin." },
      ],
      proofStats: [
        { value: "slot", label: "Seleccionable" },
        { value: "slug", label: "Link público" },
        { value: "flag", label: "Pago pendiente/ok" },
      ],
      faqs: [
        { q: "¿Historia clínica?", a: "No. Solo citas y pago." },
        { q: "¿CRM?", a: "Pipeline comercial es otro producto." },
        { q: "¿Mercado Pago?", a: "Se diseña aparte con idempotencia." },
      ],
      notIncludes: ["expediente clínico", "CRM pipeline", "catálogo WhatsApp"],
    },
    plans(
      "Planes · Agenda",
      "Para profesionales y estudios.",
      "Reservas claras, sin software clínico.",
      "cards-2",
      [
        {
          id: "pro",
          name: "Pro",
          price: 49,
          unit: "mes",
          description: "Un profesional.",
          features: ["Slots", "Reservas", "Link público"],
          cta: { label: "Empezar", href: "/login?mode=agenda" },
        },
        {
          id: "studio",
          name: "Studio",
          price: 89,
          unit: "mes",
          description: "Varios profesionales.",
          features: ["Más agendas", "Pago flag", "Admin"],
          highlight: true,
          cta: { label: "Elegir Studio", href: "/login?mode=agenda" },
        },
      ],
    ),
    "/login?mode=agenda",
    ["step-pulse", "counter", "lane-slide"],
    { display: "serif" },
  ),

  mod(
    "mantenimiento",
    "plant-ot",
    tone("#78716C", "#FAFAF9", "#57534E", "paper"),
    ["hero", "trust", "job", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Mantenimiento",
      title: "Activos.",
      titleAccent: "OT preventivo.",
      body: "Equipos, planes preventivos y órdenes técnicas — no es producción de taller.",
      trust: ["Activos", "Preventivo", "OT técnica"],
      sectionTitles: {
        job: "Cuidar la planta",
        flow: "Del plan a la OT",
        proof: "Menos paradas sorpresa",
        faq: "Mantto vs taller",
        cta: "Programa tu preventivo",
      },
      highlights: [
        { title: "Activos", body: "Equipos con historial." },
        { title: "Planes", body: "Preventivo programado." },
        { title: "OT", body: "Ejecución técnica." },
      ],
      steps: [
        { n: "01", title: "Activos", body: "Alta de equipos." },
        { n: "02", title: "Plan", body: "Frecuencia preventivo." },
        { n: "03", title: "OT", body: "Ejecuta y cierra." },
      ],
      proofStats: [
        { value: "activo", label: "Con historial" },
        { value: "plan", label: "Preventivo" },
        { value: "OT", label: "Técnica" },
      ],
      faqs: [
        { q: "¿Es Taller?", a: "Taller es producción; Mantto es preventivo de activos." },
        { q: "¿Campo?", a: "Campo es visitas comerciales; aquí son equipos." },
        { q: "¿WMS?", a: "No mueve ubicaciones de almacén." },
      ],
      notIncludes: ["OT de producción", "rutas comerciales"],
    },
    plans(
      "Planes · Mantenimiento",
      "Según activos bajo cuidado.",
      "Preventivo serio, sin mezclar producción.",
      "cards-3",
      [
        {
          id: "activo",
          name: "Activo",
          price: 69,
          unit: "mes",
          description: "Pocos equipos.",
          features: ["Activos", "OT", "Planes"],
          cta: { label: "Empezar", href: "/login?mode=mantenimiento" },
        },
        {
          id: "planta",
          name: "Planta",
          price: 139,
          unit: "mes",
          description: "Planta completa.",
          features: ["Más activos", "Preventivo", "Técnicos"],
          highlight: true,
          cta: { label: "Elegir Planta", href: "/login?mode=mantenimiento" },
        },
        {
          id: "red",
          name: "Red",
          price: 229,
          unit: "mes",
          description: "Multi-sede.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=mantenimiento",
    ["progress-fill", "step-pulse", "counter"],
    { display: "sans-tight" },
  ),

  mod(
    "recluta",
    "pipeline-hire",
    tone("#BE123C", "#FFF1F2", "#9F1239", "paper"),
    ["hero", "trust", "job", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Recluta",
      title: "Vacante.",
      titleAccent: "Candidato por etapas.",
      body: "Publica vacantes, mueve candidatos en el embudo y cierra contratación — no es CRM de ventas.",
      trust: ["Vacantes", "Etapas", "Portal"],
      sectionTitles: {
        job: "Talento, no deals",
        flow: "Del post al hire",
        proof: "Embudo de contratación",
        faq: "Recluta vs CRM",
        cta: "Abre tu próxima vacante",
      },
      highlights: [
        { title: "Vacantes", body: "Perfil y requisitos." },
        { title: "Etapas", body: "Candidato que avanza." },
        { title: "Portal", body: "Postulación externa." },
      ],
      steps: [
        { n: "01", title: "Publica", body: "Vacante y stages." },
        { n: "02", title: "Recibe", body: "Candidatos al embudo." },
        { n: "03", title: "Avanza", body: "Entrevista → hire." },
      ],
      proofStats: [
        { value: "vacante", label: "Activa" },
        { value: "stage", label: "Por candidato" },
        { value: "hire", label: "Cierre" },
      ],
      faqs: [
        { q: "¿Es CRM?", a: "CRM es deals comerciales; Recluta es talento." },
        { q: "¿ATS enorme?", a: "MVP de embudo claro, sin módulo legal pesado." },
        { q: "¿Academia?", a: "Academia capacita; Recluta contrata." },
      ],
      notIncludes: ["pipeline de ventas", "nómina"],
    },
    plans(
      "Planes · Recluta",
      "Según vacantes activas.",
      "Embudo de talento, no de ventas.",
      "cards-3",
      [
        {
          id: "vacante",
          name: "Vacante",
          price: 69,
          unit: "mes",
          description: "Pocas búsquedas.",
          features: ["Vacantes", "Etapas", "Portal"],
          cta: { label: "Empezar", href: "/login?mode=recluta" },
        },
        {
          id: "talent",
          name: "Talent",
          price: 139,
          unit: "mes",
          description: "Hiring continuo.",
          features: ["Más vacantes", "Pipeline", "Admin"],
          highlight: true,
          cta: { label: "Elegir Talent", href: "/login?mode=recluta" },
        },
        {
          id: "org",
          name: "Org",
          price: 229,
          unit: "mes",
          description: "RR.HH. a escala.",
          features: ["Onboarding", "Prioridad", "Escala"],
          cta: { label: "Hablar con ventas", href: SALES_WHATSAPP_URL },
        },
      ],
    ),
    "/login?mode=recluta",
    ["lane-slide", "step-pulse", "counter"],
    { display: "sans-tight" },
  ),

  mod(
    "atelier",
    "commerce-wa",
    tone("#DB2777", "#FDF2F8", "#BE185D", "warm"),
    ["hero", "trust", "flow", "proof", "pricing", "faq", "cta"],
    {
      badge: "Atelier",
      title: "Dibujo por encargo.",
      titleAccent: "De la idea a la entrega.",
      body: "Marketplace de ilustración: descubre creadores, cotiza, paga con Mercado Pago y sigue el pedido hasta la reseña.",
      trust: ["Portafolio", "Cotización", "Escrow lógico"],
      sectionTitles: {
        flow: "Del brief al archivo final",
        proof: "Pedido demo",
        faq: "Atelier vs catálogo",
        cta: "Explora Atelier",
      },
      highlights: [
        { title: "Creadores", body: "Perfil, servicios y portafolio." },
        { title: "Pedidos", body: "Estados claros y chat." },
        { title: "Wallet", body: "Pending → available al completar." },
      ],
      steps: [
        { n: "01", title: "Descubre", body: "Filtra por estilo." },
        { n: "02", title: "Cotiza", body: "Acepta y paga." },
        { n: "03", title: "Aprueba", body: "Revisa y reseña." },
      ],
      proofStats: [
        { value: "3", label: "Roles" },
        { value: "10%", label: "Fee default" },
        { value: "MP", label: "Checkout" },
      ],
      faqs: [
        { q: "¿Es multi-tenant SaaS?", a: "MVP es un marketplace único; schema listo para communities." },
        { q: "¿Dónde se calcula la comisión?", a: "Solo en backend (SettlementService)." },
        { q: "¿Stripe Connect?", a: "Fase 2; hoy escrow lógico + retiro manual." },
      ],
      notIncludes: ["disputas avanzadas", "payouts automáticos"],
    },
    plans(
      "Planes · Atelier",
      "Comisión sobre el pedido.",
      "Creadores y clientes sin ERP.",
      "cards-2",
      [
        {
          id: "creador",
          name: "Creador",
          price: 0,
          unit: "fee %",
          description: "Publica y cobra por encargo.",
          features: ["Portafolio", "Servicios", "Wallet"],
          highlight: true,
          cta: { label: "Entrar como creador", href: "/login?mode=atelier" },
        },
        {
          id: "cliente",
          name: "Cliente",
          price: 0,
          unit: "pedido",
          description: "Encarga y paga seguro.",
          features: ["Discovery", "Chat", "Reseñas"],
          cta: { label: "Explorar Atelier", href: "/atelier" },
        },
      ],
    ),
    "/login?mode=atelier",
    ["lane-slide", "step-pulse", "counter"],
    { display: "sans-tight" },
  ),
];
