name: Build and deploy Node.js app to Azure Web App - horytekd

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json

      - name: Install backend deps
        run: npm ci

      - name: Build client
        working-directory: client
        run: |
          npm ci
          NODE_OPTIONS=--max-old-space-size=3072 npm run build

      - name: Upload artifact (runtime only)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            index.js
            src/**
            package.json
            package-lock.json
            client/dist/**
          if-no-files-found: error
          retention-days: 2
          compression-level: 6

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact into workspace root
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_986A9A21C83B4601BF963C2F8AD4C082 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_27DC65CA76D849159297339EB562D95C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E275D2C49A3249C1A0641B18870750F1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: horytekd
          slot-name: davist-tests 
          package: .
