name: Build and deploy Node.js app to Azure Web App - horytekd

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json

      - name: Install backend deps
        run: npm ci

      - name: Build client
        working-directory: client
        run: |
          npm ci
          NODE_OPTIONS=--max-old-space-size=3072 npm run build

      - name: Upload artifact (runtime only)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            index.js
            src/**
            package.json
            package-lock.json
            client/dist/**
          if-no-files-found: error
          retention-days: 2
          compression-level: 6

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7BEB1A67DD144B47BBB2F70D4228E010 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B678AA58BAA7456BA50EFB89A0C2C139 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BB92740C4684D50AC00C42E01EE4012 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'horytekd'
          slot-name: 'davist-tests'
          package: .
          