# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Horytek

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json

      # Backend deps
      - name: Install backend deps
        run: npm ci

      # Variables y build frontend
      - name: Build frontend (Vite)
        working-directory: client
        run: |
          echo VITE_GOOGLE_MAPS_API_KEY=${{ secrets.VITE_GOOGLE_MAPS_API_KEY }} >> .env
          echo VITE_OPENROUTER_API_KEY=${{ secrets.VITE_OPENROUTER_API_KEY }} >> .env
          echo VITE_SITE_URL=${{ secrets.VITE_SITE_URL }} >> .env
          echo VITE_SITE_TITLE=${{ secrets.VITE_SITE_TITLE }} >> .env
          npm ci
          npm run build

      # Verificación mínima de assets (evita MIME issue)
      - name: Verify built assets
        working-directory: client/dist
        run: |
          test -f index.html || (echo "Falta index.html" && exit 1)
          # Extraer 1er CSS y JS y validar que existan
          for f in $(grep -Eo "assets/[A-Za-z0-9._-]+\.css" index.html | head -n1); do
            test -f "$f" || (echo "Falta asset $f" && exit 1)
          done
          for f in $(grep -Eo "assets/[A-Za-z0-9._-]+\.js" index.html | head -n1); do
            test -f "$f" || (echo "Falta asset $f" && exit 1)
          done
          echo "Assets OK"

      - name: Upload artifact (incluye dist)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            index.js
            app.js
            src/**
            package.json
            package-lock.json
            client/dist/**
          if-no-files-found: error
          retention-days: 2

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: node-app

      - name: Install production deps (backend)
        run: npm ci --omit=dev

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Horytek'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_495851EA12B441F8BF964DDDE3BCF556 }}